.TH qrl "1" "Jan 2023" "qrl VERSION" "User Commands"
.SH NAME
qrl \- open browser windows from image files containing QR codes
.SH SYNOPSIS
.PP
.B
qrl
[\fI\,OPTION\/\fR]... [\fI\,FILENAME\/\fR]...
.br
.B
qrl
[\fI\,OPTION\/\fR]...
.B \-

.SH DESCRIPTION
.PP
The program qrl opens a window that allows image files to be dragged
or pasted into it.  If an image file recognized by Java is dragged
into the drop location or appears on the command line, a QR code (if
one exists) in the image will be read and decoded to produce a URL or
text and the default browser will be "asked" to visit
that URL or display that text.  A text window displays the file names and
the URL's they encode, or a status indication if a URL cannot be
decoded. When a QR Code encodes text that is not a URL, the text will
be stored in a temporary file. For the format HTML, VCARD, and iCalendar,
the temporary file will have the file-name extensions
.BR html ,
.BR vcf ,
and
.B ics
respectively. Otherwise the extension will be
.BR txt ,
and a browser will open that file unless the
.B \-n
option is used.
.PP
The
.I FILENAME
arguments will be resolved against the current working directory for
qrl. If a file name starts with "http:", "https", of "ftp:",
the file name is treated as an absolute URI.  If a file name starts
with "file:", it will be treated as an absolute URI if the next
character is "/" and a URI relative to the current working directory
if the next character is not "/". If qrl is started via a
desktop action, it will use a system-dependent default for the current
working directory, typically the home directory of the user.
One can paste file names that are represented as text.  In this case,
there must be one file name per line.  As usual relative file names are
resolved against the current working directory.
.PP
If the only non-option argument is
.BR \- ,
file names and URLs are read from standard input, with on name or URL
per line.  For example,
.IP
.B cat files.txt | egrep '.png$' | qrl \-
.PP
will extract all the lines from the file
.B files.txt
that end with
.B .png
and arrange for
.B qrl
to  decode any QR codes and pass the URIs found to a browser.
.PP
If multiple images are provided, a browser may respond quickly to the
first but with a noticeable delay for the others. Passing a URL to a
browser is handled by the JDK and may not be available on all implementations.
If not available, one can simply paste the decoded URI into a browser.
.PP
With the
.B \-e
option, all temporary files will be removed when
.B qrl
exits. For some operating systems and browsers, and possibly JREs, this
may result in a race condition in which a temporary file is removed before
the browser opens it.  As a result, the use of the
.B \-e
option is discouraged unless the QR codes provided via the command line
encode only URIs.
.P
Finally,
.B qrl
can create QR codes. In this case, the text being encoded is read from
standard input and must be UTF-8 encoded. An output file, which must
include a file-name extension indicating the image type is specified with
the
.B \-o
option, which must be present to create a QR code.  The
.BR \-w ,
.BR \-h ,
and
.B \-L
options are described below and are optional.
.SH OPTIONS
.PP
The options for reading QR codes are
.TP
.B \-\-
End of options.  This is useful if a command line argument immediately
following the options is the file name "-n" or "-p".
.TP
.B \-e
Exit immediately after processing files and URLs provided on the
command line instead of opening a window. Unless suppressed by a
.B \-n
option, URLs found by decoding QR codes will be opened by a browser
(on systems that support this).
.TP
.BI \-d\  CWD
Set the current working directory for QRL to
.IR CWD .
This directory will be used to resolve relative file names, but
not URLs or URIs except for
.B file
URLs.
.TP
.B \-n
Do not launch a web browser and instead just list the image files and
the URL they encoded or some status and possibly error messages if a
URL cannot be found.  If the
.B \-e
option is in effect with the
.B \-n
option, the
.B \-p
option is implied.
.TP
.B \-p
Automatically print the file names and corresponding URLs or status to
standard output.
.P
The options for writing QR codes are
.TP
.BI \-i\  PATHNAME
The path name for the input file. If missing, standard input is used.
.TP
.BI \-o\  PATHNAME
The path name for the output file.
.TP
.BI \-w\  WIDTH
The width of the QR CODE in pixels. The default is 100.
.TP
.BI \-h\  HEIGHT
The height of the QR CODE in pixels. The default is 100.
.TP
.BI \-L\  LEVEL
The error-correction level for the QR code. Legal values are
.B L
(allow for up to 7% damage),
.B M
(allow for up to 15% damage),
.B Q
(allow for up to 25% damage), and
.B H
(allow for up to 30% damage).
.TP
.B \-t
The input will be trimmed by removing leading and trailing whitespace.
This is useful when generating a QR code for a URI. 
.SH AUTHOR
Written by Bill Zaumen, using the XZing library for decoding QR
codes.
\"  LocalWords:  qrl fI fR URL's TP CWD http https URIs JDK URI XZing
\"  LocalWords:  Zaumen
